import type { Metadata } from 'next'
import { FC, ReactNode } from 'react'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <html lang="en-gb">
            <body className={GeistSans.className}>{children}</body>
        </html>
    )
}

export default RootLayout
